<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-H0OUOOC" failures="1" tests="6" name="com.ASTL.TestNG.PracticeTest" time="4.204" errors="0" timestamp="2023-09-20T17:35:49 IST" skipped="3">
  <testcase classname="com.ASTL.TestNG.PracticeTest" name="createTest" time="1.181">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.fail(Assert.java:115)
at com.ASTL.TestNG.PracticeTest.createTest(PracticeTest.java:13)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- createTest -->
  <system-out/>
  <testcase classname="com.ASTL.TestNG.PracticeTest" name="createTest" time="0.733">
    <skipped/>
  </testcase> <!-- createTest -->
  <system-out/>
  <testcase classname="com.ASTL.TestNG.PracticeTest" name="createTest" time="0.565">
    <skipped/>
  </testcase> <!-- createTest -->
  <system-out/>
  <testcase classname="com.ASTL.TestNG.PracticeTest" name="createTest" time="0.567">
    <skipped/>
  </testcase> <!-- createTest -->
  <system-out/>
  <testcase classname="com.ASTL.TestNG.PracticeTest" name="editTest" time="0.484"/>
  <system-out/>
  <testcase classname="com.ASTL.TestNG.PracticeTest" name="deleteTest" time="0.674"/>
  <system-out/>
</testsuite> <!-- com.ASTL.TestNG.PracticeTest -->
